### ISSUE TITLE
[Enhancement] Inform users about Windows 2083 URL length limit

### ISSUE THREAD

**Issue by Athanasius** [taleden/EDSY#1]
To aid those users who fail to import a build from EDMC and the like due to hitting the Windows 2083 character limit on URLs under some circumstances I propose.

1. If the base64 decode step fails
1. then if the full URL length (including the `https://edsy.org/...` part) is exactly 2083 characters
1. then inform the user about the Windows 2083 URL length limit.

NB: I've now realised that *perhaps*, under some circumstances, EDMC 4.0.x.0 might have an extra issue with this that older, Python 2.7 based, EDMC didn't.  *I* can still open 'long' URLs with Firefox 78.0.2 on Windows 10 without issue though.  Either way we'll want to come up with a good set of instructions on how to avoid the issue.

**Comment by Athanasius** [comment]
See this EDMC issue for some example URLs that hit the limit on one user's Windows 7 machine, despite using Firefox: https://github.com/EDCD/EDMarketConnector/issues/617

**Comment by atfrase** [comment]
Good idea, thanks for the suggestion! This should be added in the next update.

**Comment by taleden** [comment]
Good idea, thanks for the suggestion! This should be added in the next update.

**Comment by Athanasius** [comment]
Note that we're adding an option to attempt a workaround in 4.0.3 (not yet released):

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3-rc3

I'll try to remember to update you when that's released so you can include a link to an EDMC Wiki Troubleshooting bit I'll write for it :) .

**Comment by Athanasius** [comment]
EDMC 4.0.3 is out, and I've documented the option at [https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#import-failed-no-ship-loadout-found](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#import-failed-no-ship-loadout-found)

**Comment by taleden** [comment]
Finally got around to pushing this out with v3.7.4.1; truncated imports should now generate a warning. Thanks!
