### ISSUE TITLE
Exporting build with an experimental modification fails

### ISSUE THREAD

**Issue by Kriper1111** [taleden/EDSY#10]
This happens with any experimental effect on any module.
The traceback in console says:
```
Uncaught TypeError: attribute is undefined
    getExperimentalAttrModifier https://edsy.org/edsy.js:1323
    getEffectiveAttrModifier https://edsy.org/edsy.js:1333
    exportJournal https://edsy.org/edsy.js:1824
    exportJournal https://edsy.org/edsy.js:2868
    exportSLEF https://edsy.org/edsy.js:2891
    showUIExportPopup https://edsy.org/edsy.js:5163
    onUIFitSettingsOpsClick https://edsy.org/edsy.js:9952
```
And with breakpoints on exceptions enabled, `attr` value on that line is equal to `"name"`. It somehow tries to get a numeric value of experimental modification's name.. And fails, weirdly enough.

Works as of cb8c30506aa8c08ddc23f907c13fd8ccf9453928 , doesn't happen if https://github.com/taleden/EDSY/blob/cb8c30506aa8c08ddc23f907c13fd8ccf9453928/edsy.js#L1824 is reverted.

**Comment by taleden** [comment]
Thanks for the report! This should be fixed now in 3.8.14.8.
