### ISSUE TITLE
Export blueprint/material to EDOMH

### ISSUE THREAD

**Issue by animalet** [taleden/EDSY#11]
Would be great to be able to export the retrofit report result to ED Odyssey Material Helper. This way you can track the materials you need without entering any input manually. This is especially useful for unfinished or partial builds.

**Comment by taleden** [comment]
This sounds like a good idea to me and should be pretty doable on my end, but it'll require some changes in EDOMH as well. Currently EDOMH can only accept information about a single ship at a time, but EDSY's retrofit calculator can process multiple retrofits simultaneously (and will aggregate the materials needed for all engineering rolls across all of them). I've reached out to the author, so we'll see what they think.

**Comment by taleden** [comment]
Unfortunately the author of EDOMH believes that it won't be possible for them for add support for receiving multiple ships' worth of retrofit data at once, but I can probably at least add an export button that's only enabled in the case where you've only included a single ship in the retrofit analysis.

Another option would be to ask them to add support for pasting a text-only (tab delimited) listing of the retrofit steps or materials totals. You can copy these to your clipboard using the "arrow-to-clipboard" buttons in the top right corners of the retrofitter "Checklist" and "Materials" headers. EDOMH would just need to add a text box to paste them into, and support for parsing their content.

**Comment by animalet** [comment]
> Unfortunately the author of EDOMH believes that it won't be possible for them for add support for receiving multiple ships' worth of retrofit data at once, but I can probably at least add an export button that's only enabled in the case where you've only included a single ship in the retrofit analysis.

Maybe for multi-ship, they could receive each ship as a different wishlist... just saying.

> Another option would be to ask them to add support for pasting a text-only (tab delimited) listing of the retrofit steps or materials totals. You can copy these to your clipboard using the "arrow-to-clipboard" buttons in the top right corners of the retrofitter "Checklist" and "Materials" headers. EDOMH would just need to add a text box to paste them into, and support for parsing their content.

This is also a good one, but it requires more than just "clicking a button"

**Comment by taleden** [comment]
I agree that exporting multiple ships in one click would be better, and I believe it would work on most user's platforms. However, the author of EDOMH believes that encoded export URLs exceeding 2kb will break, and even a single ship's worth of engineering can approach that limit (at least when using the encoding style that EDOMH accepts).

As far as I know only Microsoft Edge actually limits URLs to 2kb, all other modern browsers allow at least 64kb, so I personally don't think that would be a common problem. But EDOMH would need to be updated to accept a slightly different structured format, so until they're convinced to try it, the best I can do is a single ship or the clipboard.

**Comment by animalet** [comment]
That'll work

**Comment by taleden** [comment]
I've added an EDOMH export link for retrofit reports, but it's only enabled when there's only a single ship in the report. I've also added a complete JSON structured format for retrofit report exports, so the author if EDOMH is free to implement a way to copy-paste that to get multiple ships at once.

**Comment by animalet** [comment]
Great! Thanks so much.
