### ISSUE TITLE
Incorrect module prices

### ISSUE THREAD

**Issue by ultimatespirit** [taleden/EDSY#27]
Hey, I wasn't sure where EDSY pulled its price data from, so apologies if this isn't actually an issue with EDSY / something you can fix.

I noticed that the rebuy price EDSY reported for my imported python ship build was slightly below my actual in game reported rebuy, by a whole 4 credits. Nothing serious but I was curious why so started comparing module prices. Wanted to note down here any inaccuracies I ran into.

I'm guessing these modules got small credit adjustments over the years that never got documented, for why they're slightly off base. This is not an exhaustive list, just one of module classes that happened to be on my ship and available to buy at the station I'm at. Also some of the deviations are off-by-one only which could be rounding issues from the 15% discount display, but I include them anyway.

- Class 2 mining lasers, fixed and turreted, are incorrect. EDSY lists them with no discounts as 22,580cr and 32,580cr respectively. The ED wiki lists them as 22,576 and 32,576 however. In game my sale/purchase price for the models, at a 15% discount system, are 19,190 and 27,690 respectively, keeping in line with the wiki reported no-discount cost of 576 instead of 580. Class 1 lasers, abrasion blasters, and seismic launchers have correct values.
- Pulse Wave Analysers all seem to be slightly off, in this case it seems the wiki is wrong too. The station I happen to be at at the moment is a 15% discount station so I can't with 100% accuracy report the non-discounted prices, all prices below are with 15% discount. It also does not have a C rated PWA available for purchase, so I can't list its price.

| Rank | EDSY (15% discount) | Actual (15% discount) |
|:----:|:-------------------:|:---------------------:|
|  0E  |        11,518       |         11,513        |
|  0D  |        34,536       |         34,539        |
|  0B  |       310,845       |        310,844        |
|  0A  |       932,535       |        932,531        |

- Some cargo racks too:

| Rank | EDSY (15% discount) | Actual (15% discount) |
|:----:|:-------------------:|:---------------------:|
|  1E  |           850       |            850        |
|  2E  |         2,763       |          2,763        |
|  3E  |         8,976       |          8,979        |
|  4E  |        29,181       |         29,179        |
|  5E  |        94,835       |         94,832        |
|  6E  |       308,202       |        308,203        |
|  7E  |     1,001,657       |      1,001,657        |
|  8E  |     3,255,390       |      3,255,387        |

- There are way too many Shield Generators for me to go through checking them right now, my 5D Shield Generator was incorrect however. In game price with 15% discount is 160,680 and EDSY price is 160,684.
- Similarly, Fuel Scoop 4B in game price (w/discount) is 608,253 and EDSY price is 608,252.
- 6A Power Plant in game is 11,025,433, on EDSY it's 11,025,435
- 6A Thrusters in game are 13,752,602, on EDSY they're 13,752,601
- 5A FSD SCO in game are 5,206,032, on EDSY they're 5,206,029
- 4D Life Support in game are 24,118, on EDSY they're 24,115
- 7A Power Distributor in game are 8,272,137, on EDSY they're 8,272,141
- 6D Sensors in game are 189,078, on EDSY they're 189,074
- 5C Fuel Tanks in game are 83,091, on EDSY they're 83,088

- The following are a list of modules that were on my ship and had the correct values, I did not investigate other modules of different sizes / ranks for them:
   - Collector limpet controller 5D
   - Frame Shift Wake Scanner 0C
   - Prospector Limpet Controller 3A
   - Operations Limpet Controller 3C
   - Refinery 2A
   - Detailed Surface Scanner 1I

Adjusting for all of the above brought my EDSY purchase price of 89,792,356 down to 89,792,351 with a listed rebuy of 4,489,618 versus the in game rebuy of 4,489,622 (at 5% rebuy rate).

Which still didn't fix the rebuy discrepency so I looked at the ship cost and well...

- Python 15% discount in game price: 48,431,453, wiki listed price: 56,978,180 (85% of which matches in game price)
- EDSY Python 15% price: 47,018,643, no discount price: 55,316,050

So... that's a really large amount off, and definitely doesn't solve my rebuy cost calculation issue of not being able to figure out why it's 4 credits off in EDSY, considering an over 1 million discrepency adds way more than 4 credits to your rebuy...

EDIT: Oh, the ship purchase price is probably including all the base parts it comes with that you could sell off doesn't it?

EDIT2: Okay yea, it includes the module costs of the stock build so the EDSY value for the Python hull itself is the remainder after removing those parts. Without 15% discount the stock python is listed with the correct cost of 56,978,180.

_With_ the 15% discount however it sums up to 48,431,458 instead of 453, presumably due to the modules being subtly wrong in price or pointing to an issue with the 15% discount prices. Going through and listing those again...
- We already know the 5E and 4E cargo racks are wrong, as well as the 5C fuel tank.
- The 6E Shield Generator is wrong, 169,785 in game, 169,788 on EDSY
- 1E Supercruise Assist is 7,753 in game, 7,752 on EDSY
- 1F Pulse Lasers are okay
- 7E Power Plant in game is 408,350, on EDSY 408,349
- 6E Thrusters, 169,785 in game, 169,788 on EDSY
- 5E FSD: 53,561 in game, 53,559 on EDSY
- 4E Life Support: 9,647 in game, 9,648 on EDSY
- 7E Power Distributor: 211,767 in game, 211,769 on EDSY
- 6E Sensors: 75,632 in game, 75,633 on EDSY

That works out to 48,431,447, or 6 credits off the in game listed price. Implying the python has a price of 47,018,649 instead of 643.

Which still isn't enough to explain the 4 rebuy cost discrepency...

**Comment by taleden** [comment]
Way back when E:D Shipyard was first in development (in ... checks notes ... early 2015, wow) I went through several cycles of surveying every single module price in-game, because they seemed to keep changing. Every few weeks, or maybe every patch, they'd fluctuate by +/- 5 credits or something silly, so eventually I gave up and just rounded all the module prices off to the nearest 10 credits and figured it was close enough for practical purposes.

I still don't know if that was a fluke back then that stopped happening eventually, or if it's related to the background economy of the game somehow, or your reputation level with the starport, or what; if you observe that prices for some basket of modules (let's say, one each from weapons, utilities, core components, and optional internals) remains constant across several weeks and at different starports (in different systems, belonging to different superpowers) then I'll be happy to make one more complete run through everything and get them all exactly right. But if they're still fluctuating here and there, then there's no point, it'll be impossible to get them exact down to the credit. :)

**Comment by ultimatespirit** [comment]
I've been trying really hard, and failing, to play the game instead of turning it on and getting bogged down in documenting random things about it haha. Sounds like I'll have an excuse to periodically look at module costs now. I'm fairly new in the game though so probably won't have much distance spread yet, I'll see what sort of data I can get.

For what it's worth though, with regards to my original thing of trying to figure out why the rebuy cost is off... It seems rebuy costs are just off in general. I purchased an Adder in a 15% discount system for 74,637. The game reports a sale price of 67,173, which is exactly 90% of the purchase price, but a rebuy cost of 3,735, 3-4 above the 5% rebuy value of 3,731.85.

Annoyingly enough, that's not consistent between ships though, it's always 1-4 above what 5% should be but not consistently so. My best guess is some sort of iterative rounding up error arising from internal game math rounding up after every operation, making multiplication non-commutative and adding an "error" per every internal step. That should only really be able to explain a +2 deviation though, I'll need to record values from a non-discounted system sometime to check if discounts are what lead to weird math.

**Comment by ultimatespirit** [comment]
Okay, seems I've already found some discrepancies. After the Thursday tick / patch it seems some of the modules I had recorded values for and shipping costs for last week have subtly changed in price. At least I don't think I had so many measurement errors in my notes of off by 1 / wrong numbers. One of the modules increased in price by 100 credits by my notes though, so I'm not going to write off my just making a notation error and having typos until I get another week or two of data.

Interestingly enough though if I truly made no errors and they did fluctuate a bit, this would imply that even things already purchased adjust in price as these are the values of my stored modules. Ships seem to have a fixed cost at least so perhaps the interior ship chasis increases/decreases in price internally to account for pre-fitted module prices drifting slightly over time. This is such a bizarre system...

**Comment by Arcitec** [comment]
Shifts by a few credits are part of the background simulation when dealing with commodities.

So it makes perfect sense that the same thing happens for ships and modules.

Most likely, Frontier considered making the fluctuations way bigger from station to station, and they clearly have the code for that, but then they obviously decided to keep them basically the same, so they probably set the fluctuation range to something low like +/- 10 credits.

This is just my theory but it makes sense with everything above.

**Comment by taleden** [comment]
Since the state of things still seems to be that nothing holds its exact same price for more than a few weeks, I'm going to stick to my round-to-10 strategy and close this for now.

If in the future you learn that some subset of modules really do have constant, unchanging prices, please re-open and I'll take another look!
