### ISSUE TITLE
Toggle: Reverse module sorting

### ISSUE THREAD

**Issue by Arcitec** [taleden/EDSY#32]
I really wish EDSY had a "reverse sort module sizes" option. Coriolis has a great display. EDSY feels backwards, having to scroll all the way down and to the right for the best ones.

Could it be added as a user settings toggle, which simply reverses the sort order of every module type?

## EDSY

![image](https://github.com/user-attachments/assets/a155a48a-5172-40a9-a017-96fd9ec4be9b)

## Coriolis

![image](https://github.com/user-attachments/assets/224f54d1-0598-4224-a389-2783f4eb5703)

**Comment by taleden** [comment]
This option (plus reversing the horizontal rating order) is now added (by c7468350bb49bd721c2197ee523e169c3e21e34c). Thanks!

**Comment by Arcitec** [comment]
Thank you, I'm sorry I was away from the game and didn't see the update. The new sorting options are so good! 💃
