### ISSUE TITLE
Add "Hide Small Modules" button to main GUI

### ISSUE THREAD

**Issue by Arcitec** [taleden/EDSY#33]
This is *almost* a great feature but is incredibly inconvenient:

![image](https://github.com/user-attachments/assets/bc43e1c1-a6d4-45a8-bd5e-877263092000)

Instead, let's put a button here which toggles that feature on/off directly from the module picker:

![image](https://github.com/user-attachments/assets/720a407f-fa2d-4976-8cd6-4e7376d3c718)

Then people can select small power plants but large cargo racks without a bunch of tedious jumping in and out of the settings panel.

**Comment by taleden** [comment]
I approached this problem in a slightly different way (in 58f4edeca93e1544975f4670c603c9198d991125), by extending the "Hide Small Modules" option to add a "Most" setting which hides undersized modules except for Power Plants, Thrusters, and Power Distributors. If you have a use case that isn't suitably addressed that way, please re-open and describe. Thanks for the suggestion!

**Comment by Arcitec** [comment]
That is a genius idea, the new solution is so useful. No toggling needed. 😍
