### ISSUE TITLE
New FSD modules

### ISSUE THREAD

**Issue by CMDR-Cometborne** [taleden/EDSY#4]
Can you please add the new double-engineered FSD that were added this week.  Stats are:

![image](https://user-images.githubusercontent.com/25147462/141494663-0ecbe3fe-8b86-442c-be96-9a71e84f0761.png)

![image](https://user-images.githubusercontent.com/25147462/141494730-928b7c5c-9df6-46ec-9a97-0eb455f9dbc4.png)

![image](https://user-images.githubusercontent.com/25147462/141494792-d3620c8b-604d-4850-a923-0dcfcaafd062.png)

**Comment by BCLV4** [comment]
+1

**Comment by kestrel-one** [comment]
@CMDR-Cometborne @BCLV4 new FSDs have been added

**Comment by taleden** [comment]
Added by #5 and released in v3.8.3.1. Thanks for the data!

**Comment by BCLV4** [comment]
Great ! Thanks
