### ISSUE TITLE
Removing engineering blueprint does not remove its effect

### ISSUE THREAD

**Issue by ultimatespirit** [taleden/EDSY#40]
It appears in the latest changes to engineering effects on modules some edge case got broken. If you have a module with some engineering blueprint applied to it and you then select "no blueprint", the UI for applying engineering will reflect as if engineering was removed. However, the stats will remain with engineering applied and the module list would show it with the engineered icon still.

Tested on v4.19.0.1 with power distributor and life support modules, did not try replicating on every type of module, it's likely broken on all of them.

Steps to Reproduce:
- Select a module
- Apply some engineering effect to it
- Remove the effect by choosing "(No Blueprint)"
- Observe the stats are still different in the stats display

**Comment by taleden** [comment]
Do you have Experimental Mode enabled in the Help/Options tab? If so, then this is expected behavior: in Experimental Mode you can play with module attribute modifiers regardless of applied blueprint.

With Experimental Mode disabled, when I remove the blueprint from a module, I do see all modifiers being erased as well. Let me know if you're seeing different!

**Comment by ultimatespirit** [comment]
Ah ha! Yea that explains it, I had experimental mode on (was experimenting with the Cobra Mk5 loadout, easiest way to do that seems to be running experimental mode on some ship large enough slots wise... I guess I could just modify `eddb.js` locally too for ship-loadout tests...). I personally think it's a little counter-intuitive in experimental mode for removing a blueprint to not remove said blueprint's effects, when adding the blueprint does add its effects / change effects, but makes sense that this is intended behaviour in experimental mode.

Thanks for clearing that up!
