### ISSUE TITLE
Features FRAME SHIFT DRIVE (SCO)(PRE-ENGINEERED)

### ISSUE THREAD

**Issue by GLWine** [taleden/EDSY#42]
I share the features of the new SCO-V1 with what is indicated in the game.

@taleden I hope they are useful for the implementation in EDSY.

<details>
<summary>Statistics of the various levels</summary>

![2A](https://github.com/user-attachments/assets/27d4092f-5c3f-41ee-8d9c-ef654f3313be)
![2B](https://github.com/user-attachments/assets/3fee04ad-c636-4477-b429-d8208c5c5d6e)
![3A](https://github.com/user-attachments/assets/0276c260-287d-4922-a2b8-a506a634aec0)
![3B](https://github.com/user-attachments/assets/3ac4b1da-8222-4e62-b89a-e1d78777c32c)
![4A](https://github.com/user-attachments/assets/3243768c-ac9d-4cce-8c7b-37651b184b93)
![4B](https://github.com/user-attachments/assets/287141fc-f3c9-4e96-9b23-ca8502eba39b)
![5A](https://github.com/user-attachments/assets/a9fe3c2f-341b-4f0e-aa39-91427c432ccd)
![5B](https://github.com/user-attachments/assets/98c0624e-9762-4948-9717-c1e325837005)
![6A](https://github.com/user-attachments/assets/492a7e7d-1882-4cdc-979c-0a1f24f22a7b)
![6B](https://github.com/user-attachments/assets/c914f4ff-9334-4b2a-a7f9-d7a4be74761d)
![7A](https://github.com/user-attachments/assets/d458d42b-c24f-4a4f-9774-e8858c33ff17)
![7B](https://github.com/user-attachments/assets/6faf3541-25ec-4086-927e-fe57e7e49ec5)

</details>

**Comment by taleden** [comment]
These are added now. Thank you!
