### ISSUE TITLE
New multi-limpet controllers

### ISSUE THREAD

**Issue by CMDR-Cometborne** [taleden/EDSY#8]
Update 9 added a bunch of new modules.  A collection of screengrabs of their capabilities can be found here:

https://drive.google.com/drive/folders/1l4yPiLzbP8QZmxrlkD6ZqjNdtzjBCpuz?usp=sharing

The screenshots were taken at Jameson Memorial in ShinDez on an account with an elite rank, so they have both the SD discount of 10% as well as the elite rank discount of 2.5% applied.

None of the modules can be engineered.

**Comment by taleden** [comment]
Thanks for the link! Since the in-game module category is still nameless and several of these modules seem to have... odd attribute values, I'll give it a few days before adding them to see if FDev updates them.

**Comment by taleden** [comment]
Added in v3.8.4.1. Thanks!
