### ISSUE TITLE
Mass incorrect for already fitted pre-engineered Heat Sink Launcher with double Ammo Capacity

### ISSUE THREAD

**Issue by DarkmanReturns** [taleden/EDSY#9]
Any ships in your fleet which already have the pre-engineered Heat Sink Launcher with double Ammo Capacity fitted will be displayed with the correct stats for the Heat Sink Launcher except the mass, which is displayed as 2.6 T, i.e. the mass of the original Heat Sink Launcher engineered with Ammo Capacity.

Likewise if you save that ship loadout on EDSY, when you reload it you will note the mass is showing 2.6 T.
![Heat Sink](https://user-images.githubusercontent.com/84594281/207412374-a19a1f7c-5e7b-4e90-a3df-7f6f609058eb.png)

**Comment by taleden** [comment]
This should be fixed now in 3.8.14.3. Thanks for the report!

**Comment by DarkmanReturns** [comment]
Confirmed fixed as you descibed on FDev forum. Thank you again.
